* OmniFocusScripts
Various scripts to automate and enhance OmniFocus

* Sources
Many of these scripts came from other developers, and I have modified them for my use.

* Install
I have a parent Makefile which will install the scripts in the proper places.
- OmniFocus2 Application Scripts :: OmniFocus uses the =~/Library/Application\
     Scripts/com.omnigroup.OmniFocus2/= folder to look for scripts eligible to place in
     the Toolbar. Only the scripts I most use install here.
- Script Menu Application Scripts :: The standard macOS Script Editor uses the
     =~/Library/Scripts/Applications/OmniFocus= folder for the Scripts Menu. I install
     only other, less commonly used, scripts here.

* Scripts
** Templates
I forked my templates script from https://github.com/lemonmade/templates. I changed mostly
cosmetic, but I did fix some Makefile inconsistencies and a First Run Templates Folder
finding.
* License
MIT - for my scripts and edits to existing scripts. Other scripts retain their original
license.
