build: Defer\ Process\ to\ Zero\ to\ Today.applescript
	rm -f Defer\ Process\ to\ Zero\ to\ Today.scpt
	osacompile -o Defer\ Process\ to\ Zero\ to\ Today.scpt Defer\ Process\ to\ Zero\ to\ Today.applescript


install: build
	rm -f ~/development/Hazel-Scripts/Defer\ Process\ to\ Zero\ to\ Today.scpt
	cp Defer\ Process\ to\ Zero\ to\ Today.scpt ~/development/Hazel-Scripts/Defer\ Process\ to\ Zero\ to\ Today.scpt
